### ISSUE TITLE
Make a sample schema for database

### ISSUE THREAD

**Issue by celiaxiao** [cse110-fa21-group31/cse110-fa21-group31#22]
make the schema matches search filter

**Comment by XiiinSheng** [comment]
11/5/2021
![schema drawio](https://user-images.githubusercontent.com/57552802/140570183-98575cca-9c72-48e0-bb69-e9bca0b93e2a.png)

**Comment by celiaxiao** [comment]
Need to ask TA about having tags as a separate table

**Comment by XiiinSheng** [comment]
![schema drawio](https://user-images.githubusercontent.com/57552802/141522568-4a338190-06bb-4bdc-98ce-24e0a0167703.png)

Updated sample schema:
1. Kept Tag table, for a clearer database structure. 
2. Added array of savedRecipe in User table, in order to distinguish between recipes the user saved and created. 
3. Removed password from User table, and added profilePicture, which comes from the input of Google login api. 
4. Removed image from json structure of steps, as we won't allow image for every step anymore. 
5. Difficulty is kept as a tag among a few choices.
